#!/usr/bin/perl
use strict;
use warnings;
use Cwd;

#Get pwd via cwd
my $current_dir = cwd();  # Stores the current directory
print "CWD: $current_dir\n";

# Run 'dpkg -s python3' to check if Python is installed
my $check_python = `dpkg -s python3 2>/dev/null | grep Version`;

# Verify the output
if ($check_python) {
    print "Python is installed:\n$check_python";
} else {
    print "Python is NOT installed.\n";
    exit 0;
}

# If Python 3 is installed, continue with the script
my $dir = "/zephyrproject";
$current_dir .= $dir;
my $zeprodir = 0;  # Flag to track whether the directory was newly created

# Check if the directory exists
if (-d $current_dir) {
    chdir("$current_dir") or die "Failed to change directory: $!\n";
} else {
    print "The directory '$dir' does not exist. Creating it now...\n";
    mkdir $current_dir or die "Failed to create directory: $!";
    chdir("zephyrproject") or die "Failed to change directory: $!\n";
}

print "PWD: $current_dir";
# Step 1: Create the Python virtual environment
my $venv_name = ".venv";
my $status = system("bash -c '
    sudo apt install python3-venv &&
    pwd &&
    python3 -m venv $venv_name &&
    cd .. &&
    source zephyrproject/.venv/bin/activate &&
    pip install west &&
    (west init zephyrproject || echo \"Zephyr already initialized\") &&
    cd zephyrproject &&
    west update &&
    west zephyr-export &&
    west packages pip --install &&
    cd zephyr &&
    pwd &&
    west sdk install &&
    west build -p always -b nrf7002dk/nrf5340/cpuapp --source-dir $current_dir/zephyr/samples/basic/blinky_pwm --build-dir $current_dir/zephyr/build &&
    deactivate
'");
# Step 2: Activate virtual environment, install west, export zephyr to be found by cmake, install necessary modules required by python, install the west sdk and build of the project using west.
system("echo 'Virtual environment deactivated'");
exit 0;
